version: '2'
services:

  jmxtrans:
    container_name: jmxtrans
    image: jmxtrans/jmxtrans
    volumes:
      - configuration:/var/lib/jmxtrans

  argos:
    container_name: argos
    image: cloudunit/argos
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./templates:/opt/cloudunit/argos/templates
      - configuration:/opt/cloudunit/argos/configuration

volumes:
  configuration:

