env:
  global:
    - BRANCH=v1.1.0
    - DOCKER_VERSION=1.6.2

sudo: true

install:
  - curl -sLo - http://j.mp/install-travis-docker | sh -xe

script:
  - ./run 'docker build -t test . && docker run test'
  - ./run 'docker-compose up -d blog && docker ps'