---
language: java
jdk:
  - oraclejdk8

sudo: required

services:
  - docker
  
before_install: 
  - docker version
  - docker ps -a

install:
  - curl -sLo - http://j.mp/install-travis-docker | sh -xe

branches:
  only:
  - master
notifications:
  email:
  - n.muller@treeptik.fr

script: 
  # - mvn test -Dspring.profiles.active=travis -f cu-manager/pom.xml
  - ./run 'docker-compose up -d blog && docker ps'
  - ./run 'docker build -t test . && docker run test'
