sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

before_install:
- docker ps -a

script:
# - cd cu-platform && sh reset-all.sh -y
# - cd .. && mvn test -P integration -f cu-manager/pom.xml
- pwd
- env
- mvn test -f cu-manager/pom.xml --quiet


