---
language: java
jdk:
- oraclejdk8

sudo: required

services:
  - docker
  
before_install:
  - docker ps -a
  
branches:
  only:
  - master
notifications:
  email:
    - cukes-devs@googlegroups.com

script: 
  - cu-manager/mvn test -Dspring.profiles.active=vagrant
