---
language: java
jdk:
- oraclejdk8

sudo: required

services:
  - docker
  
before_install: 
  - docker version
  - docker ps -a
  
branches:
  only:
  - master
notifications:
  email:
    - n.muller@treeptik.fr

script: 
  - mvn test -Dspring.profiles.active=travis -f cu-manager/pom.xml
  
