sudo: required

services:
  - docker

before_install:
  - chmod 0600 ~/.gnupg/gpg.conf
  - docker ps -a

script:
- cd cu-services && ./build-services.sh all > /dev/null
- cd cu-services && ./check_build_images.sh
- docker images
