sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

before_install:
- docker ps -a
- curl -L https://github.com/docker/compose/releases/download/1.3.3/docker-compose-`uname -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin

script:
- pwd
- uname -a
- docker-compose -v
- cd cu-platform/travis && sh start-platform.sh
# - mvn test -f cu-manager/pom.xml --quiet


