version: '2'
services:
  java:
      container_name: java
      image: cloudunit/java

  redis:
      container_name: cuplatform_redis_1
      image: redis:3.0.1
      command: redis-server --appendonly yes
      volumes:
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro
      labels:
          - "traefik.enable=false"

  mysql:
      container_name: cuplatform_mysql_1
      image: mysql:5.7.4
      depends_on:
           - mysqldata
      ports:
           - "3306:3306"
      environment:
          - MYSQL_ROOT_PASSWORD
          - MYSQL_DATABASE=cloudunit
      volumes_from:
           - mysqldata
      volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
      labels:
            - "traefik.enable=false"

  mysqldata:
      container_name: cuplatform_mysqldata_1
      image: ubuntu:14.04
      volumes:
          - /home/admincu/mysql_home:/var/lib/mysql
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro
      labels:
          - "traefik.enable=false"

  tomcat:
      env_file:
          - production.env
      container_name: cuplatform_tomcat_1
      image: cloudunit/manager
      ports:
          - "8080:8080"
      user: "1000:999"
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro
          - /home/admincu/.cloudunit:/opt/tomcat/.cloudunit
          - /home/admincu/.docker:/opt/certificats
      environment:
          - CATALINA_OPTS="-Dspring.profiles.active=production"
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          - CU_JENKINS_DOMAIN=${CU_JENKINS_DOMAIN}
          - CU_GITLAB_DOMAIN=${CU_GITLAB_DOMAIN}
          - CU_KIBANA_DOMAIN=${CU_KIBANA_DOMAIN}
          - CU_NEXUS_DOMAIN=${CU_NEXUS_DOMAIN}
          - CU_SONAR_DOMAIN=${CU_SONAR_DOMAIN}
          - CU_LETSCHAT_DOMAIN=${CU_LETSCHAT_DOMAIN}
      labels:
          - "traefik.enable=false"

  cadvisor:
      container_name: cuplatform_cadvisor_1
      image: google/cadvisor:0.14.0
      environment:
          - DB_USER=root
          - DB_PASS=root
          - DB_NAME=cadvisor
      volumes:
          - /:/rootfs:ro
          - /var/run:/var/run:rw
          - /sys:/sys:ro
          - /var/lib/docker:/var/lib/docker:ro
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro
      command: --housekeeping_interval=5s
      labels:
          - "traefik.enable=false"

  gitlab:
      env_file:
          - production.env
      container_name: cuplatform_gitlab_1
      image: gitlab/gitlab-ce:8.13.5-ce.0
      volumes:
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro
          - /srv/gitlab/config:/etc/gitlab
          - /srv/gitlab/logs:/var/log/gitlab
          - /srv/gitlab/data:/var/opt/gitlab
      # Define the CU_GITLAB_DOMAIN into /etc/environment
      hostname: '${CU_GITLAB_DOMAIN}'
      #environment:
      #    GITLAB_OMNIBUS_CONFIG: |
      #        external_url 'https://${CU_GITLAB_DOMAIN}'
      labels:
          - "traefik.backend=gitlab"
          - "traefik.port=80"
          - "traefik.frontend.rule=Host:${CU_GITLAB_DOMAIN}"
      env_file:
          - production.env

  jenkins:
      container_name: cuplatform_jenkins_1
      build:
        context: cu-jenkins
      image: cloudunit/jenkins
      volumes:
          - /home/admincu/jenkins_home:/var/jenkins_home
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro
      labels:
          - "traefik.backend=jenkins"
          - "traefik.port=8080"
          - "traefik.frontend.rule=Host:${CU_JENKINS_DOMAIN}"
      env_file:
          - production.env

  traefik:
      image: traefik
      command: --web --docker --docker.domain=${CU_DOMAIN} --logLevel=INFO --docker.watch=true --docker.exposedbydefault=true
      ports:
          - "80:80"
          - "8080:8080"
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /dev/null:/traefik.toml
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro
      env_file:
          - production.env

networks:
  default:
    external:
      name: skynet
