version: '2'
services:

  cu-images:
    image: cloudunit/base-12.04
    image: cloudunit/base-14.04
    image: cloudunit/tomcat-8
    image: cloudunit/postgre-9-3
    image: cloudunit/java

  java:
      container_name: java
      image: cloudunit/java

  dnsdock:
      container_name: cuplatform_dnsdock_1
      image: tonistiigi/dnsdock:v1.10.0
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro
      ports:
          - "172.17.42.1:53:53/udp"
      command: -nameserver="8.8.8.8:53" -http=":80" -dns=":53" -verbose="true" -environment="cloud" -domain="unit"

  hipache:
      container_name: cuplatform_hipache_1
      image: tutum/hipache:0.3.1
      ports:
          - "80:80"
      volumes:
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro
      depends_on:
          - dnsdock

  redis:
      container_name: cuplatform_redis_1
      image: redis:3.0.1
      command: redis-server --appendonly yes
      volumes:
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro

  mysql:
      container_name: cuplatform_mysql_1
      image: mysql:5.7.4
      ports:
           - "3306:3306"
      environment:
          - MYSQL_ROOT_PASSWORD
          - MYSQL_DATABASE=cloudunit
      volumes_from:
           - mysqldata
      volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
      depends_on:
          - dnsdock
          - mysqldata

  mysqldata:
      container_name: cuplatform_mysqldata_1
      image: ubuntu:14.04
      volumes:
          - /var/lib/mysql
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro
      depends_on:
          - dnsdock

  nginx:
      container_name: cuplatform_nginx_1
      image: nginx:1.9.0
      ports:
          - "443:443"
      volumes:
          - ./nginx/sites-enabled:/etc/nginx/sites-enabled
          - ./nginx/cloudunit.io:/etc/ssl/cloudunit.io
          - ./nginx/log:/var/log/nginx
          - ./nginx/www:/var/www
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro
      depends_on:
          - dnsdock
          - tomcat
          - gitlab

  tomcat:
      container_name: cuplatform_tomcat_1
      image: cloudunit/manager
      ports:
          - "8080:8080"
      volumes:
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro
          - /home/admincu/.cloudunit:/root/.cloudunit
      environment:
          - CU_SUB_DOMAIN
          - CATALINA_OPTS="-Dspring.profiles.active=production"
          - MYSQL_ROOT_PASSWORD
      depends_on:
          - gitlab
          - dnsdock
          - mysql
          - java

  cadvisor:
      container_name: cuplatform_advisor_1
      image: google/cadvisor:0.14.0
      environment:
          - DB_USER=root
          - DB_PASS=root
          - DB_NAME=cadvisor
      volumes:
          - /:/rootfs:ro
          - /var/run:/var/run:rw
          - /sys:/sys:ro
          - /var/lib/docker:/var/lib/docker:ro
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro
      command: --housekeeping_interval=5s

  gitlab:
      container_name: cuplatform_gitlab_1
      image: gitlab/gitlab-ce:8.8.3-ce.0
      volumes:
          - /home/admincu/gitlab_home/config:/etc/gitlab
          - /home/admincu/gitlab_home/logs:/var/log/gitlab
          - /home/admincu/gitlab_home/data:/var/opt/gitlab
