version: '2'
services:

  cu-images:
    image: cloudunit/base-12.04
    image: cloudunit/base-14.04
    image: cloudunit/tomcat-8
    image: cloudunit/postgre-9-3
    image: cloudunit/java

  mysql:
    image: mysql:5.7.4
    networks:
        - back
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=nausicaa
      - MYSQL_DATABASE=cloudunit
    volumes:
      - /var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  tomcat:
    image: cloudunit/manager
    networks:
        - front
        - manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "8080:8080"
    environment:
      - CU_SUB_DOMAIN
      - CATALINA_OPTS="-Dspring.profiles.active=production"
      - MYSQL_ROOT_PASSWORD=nausicaa

  dnsdock:
    image: tonistiigi/dnsdock:v1.10.0
    networks:
        - front
        - back
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
    ports:
       - "172.17.42.1:53:53/udp"
    command: -nameserver="8.8.8.8:53" -http=":80" -dns=":53" -verbose="true" -environment="cloud" -domain="unit"

  hipache:
    image: tutum/hipache:0.3.1
    networks:
        - front
    ports:
        - "80:80"
    links:
        - redis:redis
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro

  redis:
    image: redis:3.0.1
    networks:
        - front
        - manager
    command: redis-server --appendonly yes
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro

networks:
  front:
    driver: bridge
  manager:
    driver: bridge
  back:
    driver: bridge
