version: '2'
services:

  java:
      container_name: java
      image: cloudunit/java

  hipache:
      container_name: cuplatform_hipache_1
      image: tutum/hipache:0.3.1
      ports:
          - "80:80"
      links:
          - redis:redis
      volumes:
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro

  redis:
      container_name: cuplatform_redis_1
      image: redis:3.0.1
      ports:
          - "6379:6379"
      command: redis-server --appendonly yes
      volumes:
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro

  mysql:
      container_name: cuplatform_mysql_1
      image: mysql:5.7.4
      depends_on:
           - mysqldata
      ports:
           - "3306:3306"
      environment:
          - MYSQL_ROOT_PASSWORD
          - MYSQL_DATABASE=cloudunit
      volumes_from:
           - mysqldata
      volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro

  mysqldata:
      container_name: cuplatform_mysqldata_1
      image: ubuntu:14.04
      volumes:
          - /home/vagrant/mysql_home:/var/lib/mysql
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro

  nginx:
      container_name: cuplatform_nginx_1
      build:
        context: nginx
      image: cloudunit/nginx
      ports:
          - "443:443"
      volumes:
          - ./nginx/sites-enabled:/etc/nginx/sites-enabled
          - ./nginx/cloudunit.io:/etc/ssl/cloudunit.io
          - ./nginx/www:/var/www
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf
          - ./nginx/log:/var/log/nginx
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro

  cadvisor:
      container_name: cuplatform_cadvisor_1
      image: google/cadvisor:0.14.0
      environment:
          - DB_USER=root
          - DB_PASS=root
          - DB_NAME=cadvisor
      ports:
        - "8081:8080"
      volumes:
          - /:/rootfs:ro
          - /var/run:/var/run:rw
          - /sys:/sys:ro
          - /var/lib/docker:/var/lib/docker:ro
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro
      command: --housekeeping_interval=5s

  gitlab:
      container_name: cuplatform_gitlab_1
      image: gitlab/gitlab-ce:8.13.5-ce.0
      ports:
          - "480:80"
      depends_on:
          - nginx
      volumes:
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro
          - /srv/gitlab/config:/etc/gitlab
          - /srv/gitlab/logs:/var/log/gitlab
          - /srv/gitlab/data:/var/opt/gitlab
      # Define the CU_GITLAB_DOMAIN into /etc/environment
      hostname: '${CU_GITLAB_DOMAIN}'
      #environment:
      #    GITLAB_OMNIBUS_CONFIG: |
      #        external_url 'https://${CU_GITLAB_DOMAIN}'

  jenkins:
      container_name: cuplatform_jenkins_1
      build:
        context: cu-jenkins
      image: cloudunit/jenkins
      ports:
         - "9080:8080"
         - "50000:50000"
      depends_on:
          - nginx
      volumes:
          - /home/vagrant/jenkins_home:/var/jenkins_home

networks:
  default:
    external:
      name: skynet
