version: '2'
services:

  cu-images:
    image: cloudunit/base-12.04
    image: cloudunit/base-14.04
    image: cloudunit/tomcat-8
    image: cloudunit/postgre-9-3
    image: cloudunit/java

  tomcat:
    image: cloudunit/manager
    ports:
      - "8080:8080"

  dnsdock:
    image: tonistiigi/dnsdock:v1.10.0
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
    ports:
       - "172.17.42.1:53:53/udp"
    command: -nameserver="8.8.8.8:53" -http=":80" -dns=":53" -verbose="true" -environment="cloud" -domain="unit"

  nginx:
    image: nginx:1.9.0
    ports:
       - "443:443"
    links:
       - tomcat:tomcat
    volumes:
       - ./nginx/sites-enabled:/etc/nginx/sites-enabled
       - ./nginx/cloudunit.io:/etc/ssl/cloudunit.io
       - ./nginx/log:/var/log/nginx
       - ./nginx/www:/var/www
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
       - /etc/localtime:/etc/localtime:ro
       - /etc/timezone:/etc/timezone:ro
