version: '2'
services:

  java:
      container_name: java
      image: cloudunit/java

  redis:
      container_name: cu-redis
      image: redis:3.0.1
      ports:
          - "6379:6379"
      command: redis-server --appendonly yes
      volumes:
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro
      labels:
        - "traefik.enable=false"

  mysql:
      container_name: cu-mysql
      image: mysql:5.7.4
      depends_on:
           - mysqldata
      ports:
           - "3306:3306"
      environment:
          - MYSQL_ROOT_PASSWORD
          - MYSQL_DATABASE=cloudunit
      volumes_from:
           - mysqldata
      volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
      labels:
            - "traefik.enable=false"

  mysqldata:
      container_name: cu-mysqldata
      image: ubuntu:14.04
      volumes:
          - /home/vagrant/mysql_home:/var/lib/mysql
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro

  cadvisor:
      container_name: cuplatform_cadvisor_1
      image: google/cadvisor:0.14.0
      environment:
          - DB_USER=root
          - DB_PASS=root
          - DB_NAME=cadvisor
      ports:
          - "8081:8080"
      volumes:
          - /:/rootfs:ro
          - /var/run:/var/run:rw
          - /sys:/sys:ro
          - /var/lib/docker:/var/lib/docker:ro
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro
      command: --housekeeping_interval=5s
      labels:
          - "traefik.enable=false"

  gitlab:
      container_name: cu-gitlab
      image: gitlab/gitlab-ce:8.13.5-ce.0
      volumes:
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro
          - /srv/gitlab/config:/etc/gitlab
          - /srv/gitlab/logs:/var/log/gitlab
          - /srv/gitlab/data:/var/opt/gitlab
      # Define the CU_GITLAB_DOMAIN into /etc/environment
      hostname: '${CU_GITLAB_DOMAIN}'
      #environment:
      #    GITLAB_OMNIBUS_CONFIG: |
      #        external_url 'https://${CU_GITLAB_DOMAIN}'
      labels:
          - "traefik.backend=cu-gitlab"
          - "traefik.port=80"
          - "traefik.frontend.rule=Host:gitlab.cloudunit.dev"

  jenkins:
      container_name: cu-jenkins
      build:
        context: cu-jenkins
      image: cloudunit/jenkins
      volumes:
          - /home/vagrant/jenkins_home:/var/jenkins_home
      labels:
          - "traefik.backend=cu-jenkins"
          - "traefik.port=8080"
          - "traefik.frontend.rule=Host:jenkins.cloudunit.dev"

  traefik:
      container_name: cu-traefik
      image: traefik
      command: --web --docker --docker.domain=cloudunit.dev --logLevel=INFO --docker.watch=true --docker.exposedbydefault=true
      ports:
          - "80:80"
          - "8080:8080"
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /dev/null:/traefik.toml

networks:
  default:
    external:
      name: skynet
