version: '2'
services:

  redis:
      container_name: cu-redis
      image: redis:3.0.1
      command: redis-server --appendonly yes
      volumes:
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro
          - redis-data:/data
      labels:
          - "traefik.enable=false"

  mysql:
      container_name: cu-mysql
      image: mysql:5.7.4
      environment:
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          - MYSQL_DATABASE=${MYSQL_DATABASE}
      volumes:
            - mysqldata:/var/lib/mysql
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
      labels:
            - "traefik.enable=false"

  tomcat:
      container_name: cu-tomcat
      image: cloudunit/manager
      user: "1000:999"
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro
          - ./.cloudunit:/opt/tomcat/.cloudunit
          - /home/$USER/.docker:/opt/certificats
      environment:
          - CATALINA_OPTS="-Dspring.profiles.active=production"
          - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
          - "CU_JENKINS_DOMAIN=${CU_JENKINS_DOMAIN}"
          - "CU_DOMAIN=${CU_DOMAIN}"
          - "CU_GITLAB_DOMAIN=${CU_GITLAB_DOMAIN}"
          - "CU_KIBANA_DOMAIN=${CU_KIBANA_DOMAIN}"
          - "CU_NEXUS_DOMAIN=${CU_NEXUS_DOMAIN}"
          - "CU_SONAR_DOMAIN=${CU_SONAR_DOMAIN}"
          - "CU_LETSCHAT_DOMAIN=${CU_LETSCHAT_DOMAIN}"
      labels:
          - "traefik.frontend.entryPoints=https"
          - "traefik.backend=manager"
          - "traefik.port=8080"
          - "traefik.frontend.rule=Host:${CU_MANAGER_DOMAIN}"

  cadvisor:
      container_name: cu-advisor
      image: google/cadvisor:0.14.0
      environment:
          - DB_USER=root
          - DB_PASS=root
          - DB_NAME=cadvisor
      volumes:
          - /:/rootfs:ro
          - /var/run:/var/run:rw
          - /sys:/sys:ro
          - /var/lib/docker:/var/lib/docker:ro
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro
      command: --housekeeping_interval=5s
      labels:
          - "traefik.enable=false"

  gitlab:
      container_name: cu-gitlab
      image: gitlab/gitlab-ce:8.14.5-ce.0
      volumes:
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro
          - gitlab-config:/etc/gitlab
          - gitlab-logs:/var/log/gitlab
          - gitlab-data:/var/opt/gitlab
          - ./cu-gitlab-ce/gitlab.rb:/etc/gitlab/gitlab.rb
      hostname: '${CU_GITLAB_DOMAIN}'
      ports:
          - "1212:22"
      environment:
        GITLAB_OMNIBUS_CONFIG: |
               external_url 'https://${CU_GITLAB_DOMAIN}'
      labels:
          - "traefik.frontend.entryPoints=https"
          - "traefik.backend=gitlab"
          - "traefik.port=443"
          - "traefik.frontend.rule=Host:${CU_GITLAB_DOMAIN}"

  jenkins:
      container_name: cu-jenkins
      build:
        context: cu-jenkins
      image: cloudunit/jenkins
      volumes:
          - jenkins-home:/var/jenkins_home
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro
      labels:
          - "traefik.frontend.entryPoints=https"
          - "traefik.backend=jenkins"
          - "traefik.port=8080"
          - "traefik.frontend.rule=Host:${CU_JENKINS_DOMAIN}"

  nexus:
      container_name: cu-nexus
      image: sonatype/nexus3:3.2.0
      volumes:
        - "nexus-data:/nexus-data"
      environment:
        - "JAVA_MIN_MEM=1024m"
        - "JAVA_MAX_MEM=1024m"
      labels:
        - "traefik.frontend.entryPoints=https"
        - "traefik.backend=cu-nexus"
        - "traefik.port=8081"
        - "traefik.frontend.rule=Host:${CU_NEXUS_DOMAIN}"

  traefik:
      container_name: cu-traefik
      image: traefik
      command: --web --docker --docker.domain=${CU_DOMAIN} --logLevel=DEBUG --docker.exposedbydefault=true --docker.watch=true
      ports:
          - "80:80"
          - "443:443"
          - "9090:8080"
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - ./cu-traefik/traefik.toml:/traefik.toml
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro
          - ./cu-traefik/certs:/certs
      labels:
        - "traefik.enable=false"

networks:
  default:
    external:
      name: skynet

volumes:
  mysqldata:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  jenkins-home:
  traefik-certs:
  redis-data:
  nexus-data:
