version: '2'
services:

  cu-images:
    image: cloudunit/base-12.04
    image: cloudunit/base-14.04
    image: cloudunit/tomcat-8
    image: cloudunit/postgre-9-3
    image: cloudunit/java

  tomcat:
    image: cloudunit/manager
    ports:
      - "8080:8080"
