---
spring:
  profiles: dev
  data:
    mongodb:
      host: 192.168.50.4
      database: cu-manager-domain
server:
  port: 8080
logging:
  level:
    root: info
cloudunit:
  orchestrator:
    base-uri: http://localhost:8081/