hipache:
    image: tutum/hipache:0.3.1
    ports:
        - "80:80"
    links:
        - redis:redis
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro

redis:
    image: redis:3.0.1
    command: redis-server --appendonly yes
    ports:
        - 6379:6379
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro

testmysql:
    image: mysql:5.7.4
    environment:
        - MYSQL_ROOT_PASSWORD=AezohghooNgaegh8ei2jabib2nuj9yoe
        - MYSQL_DATABASE=cloudunit
    ports:
        - 3307:3306
    volumes_from:
        - testmysqldata
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro

testmysqldata:
    image: ubuntu:14.04
    volumes:
        - /var/lib/mysql
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro

skydock:
    image: ubergarm/skyservices:no-expire
    command: /bin/sh -c "sleep 3 ; /go/bin/skydock -environment cloud -s /docker.sock -domain unit -name travis_skydns_1"
    volumes:
        - /var/run/docker.sock:/docker.sock
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro

skydns:
    image: ubergarm/skyservices:no-expire
    ports:
        - "172.17.42.1:53:53/udp"
    command: /go/bin/skydns -http 0.0.0.0:8080 -dns 0.0.0.0:53 -nameserver 8.8.8.8:53 -domain unit
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro


registry:
    image: registry:0.9.1
    ports:
        - "5000:5000"
    volumes:
        - /registry:/registry
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
    name: registry
    environment:
        - STORAGE_PATH=/registry
        - GUNICORN_OPTS=["--preload"]
