redis:
    image: redis:3.0.1
    command: redis-server --appendonly yes
    ports:
        - 6379:6379
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro

testmysql:
    image: mysql:5.7.4
    environment:
        - MYSQL_ROOT_PASSWORD=AezohghooNgaegh8ei2jabib2nuj9yoe
        - MYSQL_DATABASE=cloudunit
    ports:
        - 3307:3306
    volumes_from:
        - testmysqldata
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro

testmysqldata:
    image: ubuntu:14.04
    volumes:
        - /var/lib/mysql
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro

registry:
    image: registry:0.9.1
    ports:
        - "5000:5000"
    volumes:
        - /registry:/registry
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
    name: registry
    environment:
        - STORAGE_PATH=/registry
        - GUNICORN_OPTS=["--preload"]
